name : cv-seaicelead

channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pyyaml
  - wget
  - tqdm
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - torchvision
  - pip:    
      - git+https://github.com/microsoft/torchgeo.git
  # https://github.com/microsoft/torchgeo/issues/2069
  - gdown
  - rarfile
  - pycocotools
